package reticulum.parity

/**
 * Golden test vector definitions generated directly from go-reticulum/lxmf.
 * Generated by cmd/gen-golden-vectors in go-reticulum - DO NOT EDIT MANUALLY.
 */
case class GoldenCase(
  name: String,
  material: String,
  expandRounds: Int,
  workblockLen: Int,
  midstateHex: String,
  totalLenBits: Long,
  baseCandidateHex: String,
  startNonce: Long,
  targetCost: Int,
  expectedNonce: Long,
  expectedZeros: Int,
  expectedDigestHex: String,
  expectedCandidateHex: String,
  expectedRounds: Long
)

case class GoldenSha256Case(
  name: String,
  messageHex: String,
  expectedDigestHex: String
)

case class GoldenX25519Case(
  name: String,
  scalarHex: String,
  uCoordHex: String,
  expectedSharedHex: String
)

object GoldenVectors {
  val cases: Seq[GoldenCase] = Seq(
    GoldenCase(
      name = "LXMF Message - Target 1",
      material = "lxmf-msg-id-8a3b4c5d6e7f0123",
      expandRounds = 2,
      workblockLen = 512,
      midstateHex = "f21f8fad8e7d36d1e6630185fd3fe0d93801c0e2d362a62d8b14634e0c3a0b94",
      totalLenBits = 4352L,
      baseCandidateHex = "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20",
      startNonce = 0L,
      targetCost = 1,
      expectedNonce = 1L,
      expectedZeros = 2,
      expectedDigestHex = "3842d01d729f3c8bdc7fdd33d09c4751ce3fe489835e19398e508c54e163fb68",
      expectedCandidateHex = "0202030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20",
      expectedRounds = 2L
    ),
    GoldenCase(
      name = "LXMF Message - Target 2",
      material = "lxmf-msg-id-8a3b4c5d6e7f0123",
      expandRounds = 2,
      workblockLen = 512,
      midstateHex = "f21f8fad8e7d36d1e6630185fd3fe0d93801c0e2d362a62d8b14634e0c3a0b94",
      totalLenBits = 4352L,
      baseCandidateHex = "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20",
      startNonce = 0L,
      targetCost = 2,
      expectedNonce = 1L,
      expectedZeros = 2,
      expectedDigestHex = "3842d01d729f3c8bdc7fdd33d09c4751ce3fe489835e19398e508c54e163fb68",
      expectedCandidateHex = "0202030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20",
      expectedRounds = 2L
    ),
    GoldenCase(
      name = "LXMF Message - Target 3",
      material = "lxmf-msg-id-8a3b4c5d6e7f0123",
      expandRounds = 2,
      workblockLen = 512,
      midstateHex = "f21f8fad8e7d36d1e6630185fd3fe0d93801c0e2d362a62d8b14634e0c3a0b94",
      totalLenBits = 4352L,
      baseCandidateHex = "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20",
      startNonce = 0L,
      targetCost = 3,
      expectedNonce = 12L,
      expectedZeros = 3,
      expectedDigestHex = "10e5e05850cea9de2f4310785d900a4ba5670646ddecac3595ca78f5cd4d5546",
      expectedCandidateHex = "0d02030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20",
      expectedRounds = 13L
    ),
    GoldenCase(
      name = "LXMF Message - Target 4",
      material = "lxmf-msg-id-8a3b4c5d6e7f0123",
      expandRounds = 2,
      workblockLen = 512,
      midstateHex = "f21f8fad8e7d36d1e6630185fd3fe0d93801c0e2d362a62d8b14634e0c3a0b94",
      totalLenBits = 4352L,
      baseCandidateHex = "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20",
      startNonce = 0L,
      targetCost = 4,
      expectedNonce = 20L,
      expectedZeros = 5,
      expectedDigestHex = "0653f7bdd4b027e4ceea9680a96d85049d3862bfe469b2fdee0042c460532957",
      expectedCandidateHex = "1502030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20",
      expectedRounds = 21L
    ),
    GoldenCase(
      name = "LXMF Message - Target 6",
      material = "lxmf-msg-id-8a3b4c5d6e7f0123",
      expandRounds = 2,
      workblockLen = 512,
      midstateHex = "f21f8fad8e7d36d1e6630185fd3fe0d93801c0e2d362a62d8b14634e0c3a0b94",
      totalLenBits = 4352L,
      baseCandidateHex = "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20",
      startNonce = 0L,
      targetCost = 6,
      expectedNonce = 42L,
      expectedZeros = 6,
      expectedDigestHex = "021582d7937b58962c4f7c5d347ba43a5ed225ee79161543a5e4b85f854afba4",
      expectedCandidateHex = "2b02030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20",
      expectedRounds = 43L
    ),
    GoldenCase(
      name = "LXMF Message - Target 8",
      material = "lxmf-msg-id-8a3b4c5d6e7f0123",
      expandRounds = 2,
      workblockLen = 512,
      midstateHex = "f21f8fad8e7d36d1e6630185fd3fe0d93801c0e2d362a62d8b14634e0c3a0b94",
      totalLenBits = 4352L,
      baseCandidateHex = "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20",
      startNonce = 0L,
      targetCost = 8,
      expectedNonce = 350L,
      expectedZeros = 9,
      expectedDigestHex = "0074870218770b63d9cbcbb192883dadb5c3e7ee176a6f1d25f3681dc6bda80f",
      expectedCandidateHex = "5f03030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20",
      expectedRounds = 351L
    ),
    GoldenCase(
      name = "RNode Peering - Target 1",
      material = "rnode-peering-session-alpha",
      expandRounds = 1,
      workblockLen = 256,
      midstateHex = "fed58e1fe08d3cd8545a71d872b356b99a7fee6dc4ff82dc467b539eb3943dd3",
      totalLenBits = 2304L,
      baseCandidateHex = "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20",
      startNonce = 0L,
      targetCost = 1,
      expectedNonce = 0L,
      expectedZeros = 2,
      expectedDigestHex = "3420f77d19b2d1017f0e5f634e47393721f7e61ae539fa15294c4610d1371734",
      expectedCandidateHex = "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20",
      expectedRounds = 1L
    ),
    GoldenCase(
      name = "RNode Peering - Target 2",
      material = "rnode-peering-session-alpha",
      expandRounds = 1,
      workblockLen = 256,
      midstateHex = "fed58e1fe08d3cd8545a71d872b356b99a7fee6dc4ff82dc467b539eb3943dd3",
      totalLenBits = 2304L,
      baseCandidateHex = "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20",
      startNonce = 0L,
      targetCost = 2,
      expectedNonce = 0L,
      expectedZeros = 2,
      expectedDigestHex = "3420f77d19b2d1017f0e5f634e47393721f7e61ae539fa15294c4610d1371734",
      expectedCandidateHex = "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20",
      expectedRounds = 1L
    ),
    GoldenCase(
      name = "RNode Peering - Target 4",
      material = "rnode-peering-session-alpha",
      expandRounds = 1,
      workblockLen = 256,
      midstateHex = "fed58e1fe08d3cd8545a71d872b356b99a7fee6dc4ff82dc467b539eb3943dd3",
      totalLenBits = 2304L,
      baseCandidateHex = "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20",
      startNonce = 0L,
      targetCost = 4,
      expectedNonce = 17L,
      expectedZeros = 4,
      expectedDigestHex = "0c1adacd3fb060c24fabfd76bcf18f7e93e3313e7d6c5555cb84072b951f17bc",
      expectedCandidateHex = "1202030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20",
      expectedRounds = 18L
    ),
    GoldenCase(
      name = "RNode Peering - Target 7",
      material = "rnode-peering-session-alpha",
      expandRounds = 1,
      workblockLen = 256,
      midstateHex = "fed58e1fe08d3cd8545a71d872b356b99a7fee6dc4ff82dc467b539eb3943dd3",
      totalLenBits = 2304L,
      baseCandidateHex = "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20",
      startNonce = 0L,
      targetCost = 7,
      expectedNonce = 179L,
      expectedZeros = 9,
      expectedDigestHex = "006ab20e6366f69174443aae9b15b318fd9fd7e902671d8706c3de39d5b8d243",
      expectedCandidateHex = "b402030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20",
      expectedRounds = 180L
    ),
    GoldenCase(
      name = "Offset Search - Target 5",
      material = "lxmf-msg-id-8a3b4c5d6e7f0123",
      expandRounds = 2,
      workblockLen = 512,
      midstateHex = "f21f8fad8e7d36d1e6630185fd3fe0d93801c0e2d362a62d8b14634e0c3a0b94",
      totalLenBits = 4352L,
      baseCandidateHex = "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20",
      startNonce = 50L,
      targetCost = 5,
      expectedNonce = 57L,
      expectedZeros = 7,
      expectedDigestHex = "01507faa878bb2f1a2d593820b0915673864f71e4725724ca0f9315ccc6b87ba",
      expectedCandidateHex = "3a02030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20",
      expectedRounds = 8L
    ),
  )

  val sha256Cases: Seq[GoldenSha256Case] = Seq(
    GoldenSha256Case(
      name = "FIPS 180-4: Single Block 'abc'",
      messageHex = "616263",
      expectedDigestHex = "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
    ),
    GoldenSha256Case(
      name = "FIPS 180-4: 2-Block 'abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq'",
      messageHex = "6162636462636465636465666465666765666768666768696768696a68696a6b696a6b6c6a6b6c6d6b6c6d6e6c6d6e6f6d6e6f706e6f7071",
      expectedDigestHex = "248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1"
    ),
    GoldenSha256Case(
      name = "FIPS 180-4: Empty String",
      messageHex = "",
      expectedDigestHex = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
    )
  )

  val x25519Cases: Seq[GoldenX25519Case] = Seq(
    GoldenX25519Case(
      name = "RFC 7748 Vector 1",
      scalarHex = "a546e36bf0527c9d3b16154b82465edd62144c0ac1fc5a18506a2244ba449ac4",
      uCoordHex = "e6db6867583030db3594c1a424b15f7c726624ec26b3353b10a903a6d0ab1c4c",
      expectedSharedHex = "c3da55379de9c6908e94ea4df28d084f32eccf03491c71f754b4075577a28552"
    ),
    GoldenX25519Case(
      name = "RFC 7748 Vector 2",
      scalarHex = "4b66e9d4d1b4673c5ad22691957d6af5c11b6421e0ea01d42ca4169e7918ba0d",
      uCoordHex = "e5210f12786811d3f4b7959d0538ae2c31dbe7106fc03c3efc4cd549c715a493",
      expectedSharedHex = "95cbde9476e8907d7aade45cb4b873f88b595a68799fa152e6f8f7647aac7957"
    ),
    GoldenX25519Case(
      name = "Base Point u=9 with Scalar 1",
      scalarHex = "0100000000000000000000000000000000000000000000000000000000000000",
      uCoordHex = "0900000000000000000000000000000000000000000000000000000000000000",
      expectedSharedHex = "2fe57da347cd62431528daac5fbb290730fff684afc4cfc2ed90995f58cb3b74"
    ),
    GoldenX25519Case(
      name = "Reticulum Handshake Key Exchange A",
      scalarHex = "c8079d38767314f11b2a40701026702636e29618201d4fb3a6049c692a947fa5",
      uCoordHex = "504602762c4b84965378ac4790be450123963286f14dd16b270733a4e3b0d595",
      expectedSharedHex = "86633513b4ad8ecbb5e22269af2a39cefa4f39acf116767af58582b113466b1a"
    ),
    GoldenX25519Case(
      name = "Reticulum Handshake Key Exchange B",
      scalarHex = "4a5d9d5ba4ce2de1728e3bf480350f25e07e21c947d19e3376f09b3c1e161742",
      uCoordHex = "438a6800f489f1a7d0394b507c7510a976ce5439f481ac60bdab3429b59e564e",
      expectedSharedHex = "aaf91d2b8b839649e5d6ae431eeece2d5c68dae6de1bde60dce5af764500471e"
    ),
  )
}
